// Generated by ReScript, PLEASE EDIT WITH CARE

import * as H1Playroom from "../../src/typography/Heading/SubSets/h1/H1Playroom.js";

var $$default = H1Playroom.make;

export {
  $$default ,
  $$default as default,
  
}
/* H1Playroom Not a pure module */
